"""Client-side configuration for the license system.

Only the PUBLIC verification key is shipped with the app. The matching PRIVATE
signing key lives solely on the license server and must never be embedded here.
"""
from __future__ import annotations

# Product identifier reported to the license server.
PRODUCT_ID = "furniture_bill"

# App version reported during activation.
APP_VERSION = "1.0.0"

# Sample license server base URL (HTTPS in production).
LICENSE_SERVER_URL = "http://localhost:8000"

# Trial period in days; 0 disables the trial entirely (users must activate).
TRIAL_DAYS = 0

# Ed25519 PUBLIC key used to verify signed license data offline.
# Generated by license_server/app/crypto/generate_keys.py
LICENSE_PUBLIC_KEY = "vkecyAMGB6VVw0Rp2Ka8w96YqFgXxZ9dGrBuLj3KLJg="

# Local license file — deliberately OUTSIDE the SQLite data folder so a
# backup/restore of business data can never clone an activated license.
LICENSE_FILE_PATH = "%APPDATA%/FurnitureBill/license.json"